import catBags from "@/assets/cat-bags.jpg";
import catRings from "@/assets/cat-rings.jpg";
import catEarrings from "@/assets/cat-earrings.jpg";
import catNecklaces from "@/assets/cat-necklaces.jpg";
import catSunglasses from "@/assets/cat-sunglasses.jpg";
import catWatches from "@/assets/cat-watches.jpg";

import prBag1 from "@/assets/pr-bag1.jpg";
import prBag2 from "@/assets/pr-bag2.jpg";
import prRing1 from "@/assets/pr-ring1.jpg";
import prEar1 from "@/assets/pr-ear1.jpg";
import prNeck1 from "@/assets/pr-neck1.jpg";
import prWatch1 from "@/assets/pr-watch1.jpg";
import prScarf1 from "@/assets/pr-scarf1.jpg";
import type { ImageSource } from "@/lib/image";

export type Category = {
  slug: string;
  name: string;
  img: ImageSource;
  count: string;
  description?: string;
};

export type Product = {
  slug: string;
  name: string;
  brand?: string;
  category: string;
  categorySlug?: string;
  price: number;
  was: number | null;
  img: ImageSource;
  images?: string[];
  tag?: "New" | "Bestseller" | "Limited" | "Sale" | "Hot" | "Best Seller";
  rating?: number;
  reviewCount?: number;
  volume?: string;
  variants?: string[];
  sizes?: string[];
  colors?: string[];
  description?: string;
  benefits?: string[];
  howToUse?: string;
  keyIngredients?: string[];
  skinType?: string[];
  inStock?: boolean;
  stock?: number;
  stockCount?: number;
};

export type HomepageFeature = {
  icon: "truck" | "refresh" | "shield" | "sparkles";
  title: string;
  summary: string;
};

export type HomepageTestimonial = {
  name: string;
  city: string;
  quote: string;
};

export type AdminModule = {
  title: string;
  description: string;
};

export type CustomerModule = {
  title: string;
  description: string;
};

export type AuthProvider = {
  name: string;
  status: "ready" | "planned";
  description: string;
};

export type PaymentGateway = {
  name: string;
  enabled: boolean;
};

export type CourierPartner = {
  name: string;
  tracking: string;
};

export const CATEGORIES: Category[] = [
  {
    slug: "serums",
    name: "Serums & Ampoules",
    img: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800",
    count: "48 products",
    description: "Targeted glow, hyperpigmentation & barrier repair formulas",
  },
  {
    slug: "toners",
    name: "Toners & Essences",
    img: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800",
    count: "36 products",
    description: "Hydrating, soothing 7-skin method essences & toners",
  },
  {
    slug: "sunscreens",
    name: "Sun Care & SPF",
    img: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800",
    count: "29 products",
    description: "Zero-white cast, lightweight Korean sunscreens with SPF50+ PA++++",
  },
  {
    slug: "cleansers",
    name: "Cleansers & Washes",
    img: "https://images.unsplash.com/photo-1556228852-6d35a585d566?w=800",
    count: "32 products",
    description: "Gentle low-pH gel washes and cleansing oils",
  },
  {
    slug: "moisturizers",
    name: "Moisturizers & Creams",
    img: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800",
    count: "44 products",
    description: "Ceramide barrier creams, gel moisturizers & sleeping packs",
  },
  {
    slug: "masks",
    name: "Sheet Masks & Peels",
    img: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800",
    count: "25 products",
    description: "Instant glass-skin sheet masks and gentle chemical exfoliants",
  },
  {
    slug: "eye-lip-care",
    name: "Eye & Lip Treatments",
    img: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800",
    count: "18 products",
    description: "Overnight lip sleeping masks and caffeine peptide eye creams",
  },
  {
    slug: "sets",
    name: "K-Beauty Routine Sets",
    img: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800",
    count: "15 curated sets",
    description: "Step-by-step complete Korean 5-step skincare rituals",
  },
  {
    slug: "bags",
    name: "Bags & Totes",
    img: catBags,
    count: "58 pieces",
    description: "Handcrafted luxury bags and everyday totes",
  },
  {
    slug: "rings",
    name: "Jewelry & Rings",
    img: catRings,
    count: "42 pieces",
    description: "Anti-tarnish rose gold and gold pavé rings",
  },
  {
    slug: "earrings",
    name: "Earrings & Drops",
    img: catEarrings,
    count: "76 pieces",
    description: "Freshwater pearls and minimalist studs",
  },
  {
    slug: "watches",
    name: "Luxury Watches",
    img: catWatches,
    count: "22 pieces",
    description: "Timeless classic and modern mesh watches",
  },
];

export const PRODUCTS: Product[] = [
  // ─── AUTHENTIC KOREAN SKINCARE (6 Products per Category) ───
  {
    slug: "cosrx-advanced-snail-96-mucin-power-essence",
    name: "COSRX Advanced Snail 96 Mucin Power Essence",
    brand: "COSRX",
    category: "toners",
    price: 1850,
    was: 2200,
    img: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800",
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800",
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800",
      "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800",
    ],
    tag: "Bestseller",
    rating: 4.9,
    reviewCount: 382,
    volume: "100ml",
    variants: ["100ml (Standard)", "30ml (Travel Mini)"],
    description:
      "Formulated with 96.3% Snail Secretion Filtrate, this cult-favorite Korean essence protects the skin from moisture loss while improving skin elasticity. Snail mucin helps repair and soothes red, sensitive skin post-breakouts by replenishing moisture.",
    benefits: [
      "Fades dark spots and post-acne pigmentation",
      "Delivers intense multi-layer hydration with zero stickiness",
      "Calms redness and strengthens damaged skin barriers",
      "100% cruelty-free snail mucin harvested safely",
    ],
    howToUse:
      "After cleansing and toning, apply a small amount (2 pumps) onto your entire face. Gently pat using fingertips to aid absorption, then follow with your serum and moisturizer.",
    keyIngredients: [
      "96.3% Snail Secretion Filtrate",
      "Sodium Hyaluronate (Hyaluronic Acid)",
      "Panthenol (Vitamin B5)",
      "Allantoin",
      "Arginine",
    ],
    skinType: ["Dry", "Acne-Prone", "Sensitive", "Combination", "Oily"],
    inStock: true,
    stockCount: 45,
  },
  {
    slug: "anua-heartleaf-77-soothing-toner",
    name: "Anua Heartleaf 77% Soothing Toner",
    brand: "Anua",
    category: "toners",
    price: 1950,
    was: 2350,
    img: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800",
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800",
    ],
    tag: "Bestseller",
    rating: 4.88,
    reviewCount: 275,
    volume: "250ml",
    variants: ["250ml (Standard)", "500ml (Jumbo Size)"],
    description:
      "Ranked #1 Toner in Korea (Olive Young award winner). Formulated with 77% Heartleaf Extract sourced from Korea, this gentle pH 5.5 sub-acidic toner soothes irritated skin, reduces stubborn fungal acne, balances sebum, and restores moisture equilibrium.",
    benefits: [
      "Calms active breakouts, redness, and inflammation",
      "Maintains optimal sub-acidic pH balance (5.5 - 6.0)",
      "Non-comedogenic tested — safe for fungal acne and clogged pores",
      "Hypoallergenic formula with zero artificial fragrance",
    ],
    howToUse:
      "After facial cleansing, soak a cotton pad or pour into clean palms and gently wipe or pat across the face. Can also be used as a 5-minute soothing toner mask.",
    keyIngredients: [
      "77% Houttuynia Cordata (Heartleaf) Extract",
      "Centella Asiatica",
      "Chamomilla Recutita Flower Extract",
      "Panthenol",
      "Sugar Cane Extract",
    ],
    skinType: ["Acne-Prone", "Sensitive", "Oily", "Combination"],
    inStock: true,
    stockCount: 38,
  },
  {
    slug: "im-from-rice-toner",
    name: "I'm From Rice Toner (Yeoju Organic Rice)",
    brand: "I'm From",
    category: "toners",
    price: 2150,
    was: 2500,
    img: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800",
    images: [
      "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800",
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800",
    ],
    tag: "Bestseller",
    rating: 4.94,
    reviewCount: 210,
    volume: "150ml",
    variants: ["150ml Standard", "30ml Mini"],
    description:
      "Formulated with 77.78% organic Yeoju Rice extract, this milky, dual-phase hydrating toner gently eliminates dead skin flakes, balances excess oil, and leaves dull skin luminous, soft, and glassy.",
    benefits: [
      "77.78% Yeoju Rice Extract promotes clear glowing complexion",
      "Deeply hydrates and strengthens moisture barrier",
      "Soothes flaky, sun-stressed, and dehydrated skin",
    ],
    howToUse: "Shake well before use to blend the two layers, then pat onto cleansed face.",
    keyIngredients: [
      "77.78% Rice Extract",
      "Rice Bran Extract",
      "Niacinamide",
      "Adenosine",
      "Purslane Extract",
    ],
    skinType: ["Dull", "Dry", "Combination", "Sensitive"],
    inStock: true,
    stockCount: 32,
  },
  {
    slug: "haruharu-wonder-black-rice-hyaluronic-toner",
    name: "Haruharu Wonder Black Rice Hyaluronic Toner (Fragrance Free)",
    brand: "Haruharu Wonder",
    category: "toners",
    price: 1750,
    was: 2100,
    img: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800",
    images: ["https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800"],
    tag: "New",
    rating: 4.87,
    reviewCount: 145,
    volume: "150ml",
    variants: ["150ml", "300ml Jumbo"],
    description:
      "A rich, comforting toner powered by 100% Korean fermented black rice extract and bamboo shoot bark that deeply conditions and hydrates tight, thirsty skin.",
    benefits: [
      "Fermented Black Rice packs 2,000x more antioxidants than white rice",
      "Ultra Deep Technology delivers actives deep into epidermal layers",
      "100% vegan, cruelty-free and alcohol-free",
    ],
    howToUse: "Pour a moderate amount onto hands and gently press into skin until fully absorbed.",
    keyIngredients: [
      "Fermented Black Rice Extract",
      "Hyaluronic Acid",
      "Bamboo Shoot Bark Extract",
      "Beta-Glucan",
    ],
    skinType: ["Sensitive", "Dry", "Normal", "Dehydrated"],
    inStock: true,
    stockCount: 28,
  },
  {
    slug: "round-lab-1025-dokdo-toner",
    name: "Round Lab 1025 Dokdo Toner",
    brand: "Round Lab",
    category: "toners",
    price: 1890,
    was: 2250,
    img: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800",
    images: ["https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800"],
    tag: "Bestseller",
    rating: 4.91,
    reviewCount: 340,
    volume: "200ml",
    variants: ["200ml", "500ml"],
    description:
      "Award-winning gentle exfoliating toner formulated with Ulleungdo Island Deep Sea Water containing 74 natural minerals. Gently dissolves micro dead skin cells with Hatching EX-07 enzyme.",
    benefits: [
      "74 natural deep sea minerals maintain hydration balance",
      "Hatching EX-07 enzyme gently exfoliates without irritation",
      "Panthenol and Allantoin calm sensitized skin",
    ],
    howToUse: "Soak a cotton pad and gently wipe across face along the skin texture.",
    keyIngredients: [
      "Ulleungdo Deep Sea Water",
      "Hatching EX-07",
      "Panthenol",
      "Allantoin",
      "Betaine",
    ],
    skinType: ["All Skin Types", "Sensitive", "Textured"],
    inStock: true,
    stockCount: 40,
  },
  {
    slug: "klairs-supple-preparation-unscented-toner",
    name: "Dear, Klairs Supple Preparation Unscented Toner",
    brand: "Dear, Klairs",
    category: "toners",
    price: 1790,
    was: 2150,
    img: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800",
    images: ["https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800"],
    tag: "Sale",
    rating: 4.89,
    reviewCount: 290,
    volume: "180ml",
    variants: ["180ml"],
    description:
      "Essential-oil free version of the legendary Klairs toner. Formulated with a blend of botanical extracts, Centella Asiatica, and Hyaluronic Acid to hydrate, calm, and prepare skin for active serums.",
    benefits: [
      "0% Essential oils — ideal for ultra-reactive skin",
      "Deeply restores moisture level after washing",
      "Thick bouncy texture absorbs without stickiness",
    ],
    howToUse:
      "Apply generously to cleansed skin and layer 2-3 times for maximum glass-skin hydration.",
    keyIngredients: [
      "Centella Asiatica",
      "Hyaluronic Acid",
      "Licorice Root Extract",
      "Beta-Glucan",
      "Aloe Barbadensis",
    ],
    skinType: ["Sensitive", "Dry", "Acne-Prone", "Irritated"],
    inStock: true,
    stockCount: 35,
  },
  {
    slug: "axis-y-dark-spot-correcting-glow-serum",
    name: "AXIS-Y Dark Spot Correcting Glow Serum",
    brand: "AXIS-Y",
    category: "serums",
    price: 1750,
    was: 2100,
    img: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800",
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800",
      "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800",
    ],
    tag: "Bestseller",
    rating: 4.92,
    reviewCount: 310,
    volume: "50ml",
    variants: ["50ml Tube"],
    description:
      "A 5% Niacinamide-based corrective serum that corrects dark spots, melasma, and uneven skin tone. With plant-derived Squalane, this serum retains moisture to keep your skin glowing, clear, and healthy all day long in humid climates.",
    benefits: [
      "5% Niacinamide effectively fades stubborn post-acne marks",
      "Plant-derived Squalane locks in natural hydration",
      "Papaya and Sea Buckthorn brighten skin complexion naturally",
      "Non-greasy lightweight gel formula perfect for Bangladesh weather",
    ],
    howToUse:
      "Apply a small amount to the entire face or targeted dark spots. Gently pat until fully absorbed. Suitable for both morning and night routine.",
    keyIngredients: [
      "5% Niacinamide",
      "Plant-Derived Squalane",
      "Sea Buckthorn Fruit Extract",
      "Papaya Extract",
      "Rice Bran Extract",
      "Allantoin",
    ],
    skinType: ["Hyperpigmentation", "Uneven Tone", "All Skin Types"],
    inStock: true,
    stockCount: 52,
  },
  {
    slug: "skin1004-madagascar-centella-ampoule",
    name: "Skin1004 Madagascar Centella Asiatica Ampoule",
    brand: "Skin1004",
    category: "serums",
    price: 1890,
    was: 2250,
    img: "https://images.unsplash.com/photo-1617897903246-719242758050?w=800",
    images: [
      "https://images.unsplash.com/photo-1617897903246-719242758050?w=800",
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800",
    ],
    tag: "New",
    rating: 4.89,
    reviewCount: 220,
    volume: "100ml",
    variants: ["100ml (Full Size)", "55ml (Standard)"],
    description:
      "Crafted with 100% pure Centella Asiatica extract directly harvested from pristine Madagascar nature. This lightweight, watery ampoule instantly penetrates deep into skin layers to extinguish redness, heal blemishes, and repair compromised barriers.",
    benefits: [
      "100% Pure single-ingredient Madagascar Centella extract",
      "Rapidly reduces inflamed pimples and chemical irritation",
      "Balances oil and moisture production without clogging pores",
      "Zero fragrance, zero preservatives, 100% hypoallergenic",
    ],
    howToUse:
      "Drop an appropriate amount using the pipette and apply evenly across the skin. Pat gently until absorbed.",
    keyIngredients: ["100% Madagascar Centella Asiatica Extract"],
    skinType: ["Sensitive", "Acne-Prone", "Compromised Barrier", "Redness"],
    inStock: true,
    stockCount: 30,
  },
  {
    slug: "torriden-dive-in-low-molecular-hyaluronic-acid-serum",
    name: "Torriden DIVE-IN Low Molecular Hyaluronic Acid Serum",
    brand: "Torriden",
    category: "serums",
    price: 1950,
    was: 2400,
    img: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800",
    images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800"],
    tag: "Bestseller",
    rating: 4.91,
    reviewCount: 160,
    volume: "50ml",
    variants: ["50ml", "100ml Jumbo"],
    description:
      "Formulated with 5D-Complex Hyaluronic Acid of 5 varying molecular weights that instantly floods all 5 epidermal layers with hydration. Provides non-sticky, soothing moisture with Malachite extract.",
    benefits: [
      "5 different molecular sizes of Hyaluronic Acid for 3D hydration",
      "Immediate calming effect on dry, tight skin",
      "Clean beauty vegan certified formula",
    ],
    howToUse: "Dispense 3-5 drops directly onto clean skin and pat gently.",
    keyIngredients: [
      "5D-Complex Hyaluronic Acid",
      "D-Panthenol",
      "Malachite Extract",
      "Ceramide NP",
    ],
    skinType: ["Dehydrated", "Dry", "Oily-Dehydrated", "Sensitive"],
    inStock: true,
    stockCount: 35,
  },
  {
    slug: "beauty-of-joseon-glow-serum-propolis-niacinamide",
    name: "Beauty of Joseon Glow Serum : Propolis + Niacinamide",
    brand: "Beauty of Joseon",
    category: "serums",
    price: 1650,
    was: 1950,
    img: "https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=800",
    images: ["https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=800"],
    tag: "Bestseller",
    rating: 4.93,
    reviewCount: 420,
    volume: "30ml",
    variants: ["30ml"],
    description:
      "Enriched with 60% Propolis Extract and 2% Niacinamide, this honey-like serum calms inflammatory acne, tightens enlarged pores, and delivers a radiant healthy glow.",
    benefits: [
      "60% Propolis combats acne-causing bacteria and accelerates healing",
      "2% Niacinamide regulates sebum production and refines pore texture",
      "Tamanu oil and Lotus extract nourish skin barrier",
    ],
    howToUse: "Apply 2-3 drops to clean face and pat gently until absorbed.",
    keyIngredients: [
      "60% Propolis Extract",
      "2% Niacinamide",
      "0.5% BHA (Betaine Salicylate)",
      "Tamanu Oil",
    ],
    skinType: ["Acne-Prone", "Enlarged Pores", "Inflamed Skin"],
    inStock: true,
    stockCount: 48,
  },
  {
    slug: "some-by-mi-aha-bha-pha-30-days-miracle-serum",
    name: "Some By Mi AHA BHA PHA 30 Days Miracle Serum",
    brand: "Some By Mi",
    category: "serums",
    price: 1790,
    was: 2150,
    img: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=800",
    images: ["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=800"],
    tag: "Sale",
    rating: 4.86,
    reviewCount: 230,
    volume: "50ml",
    variants: ["50ml"],
    description:
      "Dual-layered exfoliating serum containing 10,000ppm Tea Tree Leaf Water, Centella Asiatica, and triple acids (AHA/BHA/PHA) to gently purge clogged pores and calm acne flare-ups.",
    benefits: [
      "Triple chemical exfoliants sweep away blackheads & sebum",
      "10,000ppm Tea Tree Water disinfects acne bacteria",
      "Plant oil layer locks in essential barrier moisture",
    ],
    howToUse: "Shake bottle well before use, apply 3-4 drops and gently massage into skin.",
    keyIngredients: [
      "Tea Tree Leaf Water",
      "Centella Asiatica (14.5%)",
      "AHA (Citric Acid)",
      "BHA (Salicylic Acid)",
      "PHA (Lactobionic Acid)",
    ],
    skinType: ["Oily", "Acne-Prone", "Blackheads", "Blemish-Prone"],
    inStock: true,
    stockCount: 26,
  },
  {
    slug: "cosrx-the-niacinamide-15-serum",
    name: "COSRX The Niacinamide 15% Serum with Zinc PCA",
    brand: "COSRX",
    category: "serums",
    price: 1850,
    was: 2200,
    img: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800",
    images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800"],
    tag: "New",
    rating: 4.88,
    reviewCount: 112,
    volume: "20ml",
    variants: ["20ml"],
    description:
      "High-potency clinical serum featuring 15% Niacinamide and Zinc PCA to visibly reduce sebum overflow, tighten stubborn pores, and lighten dark hyperpigmentation marks.",
    benefits: [
      "15% Concentrated Niacinamide visibly refines skin texture",
      "Zinc PCA regulates excess oil & prevents breakout cycles",
      "Allantoin and Trehalose soothe skin during treatment",
    ],
    howToUse: "Apply 2-3 drops to face after toner. Use SPF during daytime.",
    keyIngredients: ["15% Niacinamide", "Zinc PCA", "N-Acetylglucosamine (NAG)", "Allantoin"],
    skinType: ["Oily", "Large Pores", "Post-Acne Marks"],
    inStock: true,
    stockCount: 20,
  },
  {
    slug: "beauty-of-joseon-relief-sun-rice-probiotics-spf50",
    name: "Beauty of Joseon Relief Sun: Rice + Probiotics (SPF50+ PA++++)",
    brand: "Beauty of Joseon",
    category: "sunscreens",
    price: 1650,
    was: 1950,
    img: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800",
    images: [
      "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800",
      "https://images.unsplash.com/photo-1556228852-6d35a585d566?w=800",
    ],
    tag: "Bestseller",
    rating: 4.95,
    reviewCount: 490,
    volume: "50ml",
    variants: ["50ml (Single)", "50ml x 2 (Twin Pack)"],
    description:
      "An ultra-light organic sunscreen that applies comfortably like a light moisturizing cream. Contains 30% rice extract and fermented grain probiotics that deeply nourish the skin barrier while protecting against broad-spectrum UVA & UVB rays without any white cast or stickiness.",
    benefits: [
      "Zero white cast on South Asian skin tones",
      "Moisturizing dewy finish without greasy shine",
      "Certified broad-spectrum SPF 50+ PA++++ by Korean and Spanish labs",
      "Enriched with vitamins B, C, E and amino acids from rice",
    ],
    howToUse:
      "At the last step of your morning skincare routine, evenly spread a generous amount (two finger-lengths) over areas prone to sun exposure.",
    keyIngredients: [
      "30% Rice Extract",
      "Grain Fermented Probiotics",
      "Niacinamide (2%)",
      "Green Tea Extract",
      "Vitamin E",
    ],
    skinType: ["All Skin Types", "Dry", "Sensitive", "Combination"],
    inStock: true,
    stockCount: 60,
  },
  {
    slug: "round-lab-birch-juice-moisturizing-sunscreen-spf50",
    name: "Round Lab Birch Juice Moisturizing Sunscreen SPF50+ PA++++",
    brand: "Round Lab",
    category: "sunscreens",
    price: 1850,
    was: 2150,
    img: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800",
    images: ["https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800"],
    tag: "Bestseller",
    rating: 4.93,
    reviewCount: 185,
    volume: "50ml",
    variants: ["50ml"],
    description:
      "Hwahae App #1 Sunscreen in Korea for 3 consecutive years. Infused with Inje Silver Birch Tree Sap and Vita Hyaluronic Acid, this hydrating sunscreen acts as both an everyday moisturizer and high-grade UV shield.",
    benefits: [
      "Rich in natural amino acids and minerals from Birch Sap",
      "Cools heated skin down while blocking UV radiation",
      "Leaves skin plump, radiant and ready for makeup",
    ],
    howToUse: "Apply evenly to face and neck 15 minutes before stepping into sun.",
    keyIngredients: ["Inje Birch Tree Sap", "Hyaluronic Acid", "Niacinamide", "Adenosine"],
    skinType: ["Dry", "Dehydrated", "Combination", "Normal"],
    inStock: true,
    stockCount: 25,
  },
  {
    slug: "skin1004-madagascar-centella-hyalu-cica-water-fit-sun-serum-spf50",
    name: "Skin1004 Madagascar Centella Hyalu-Cica Water-Fit Sun Serum SPF50+ PA++++",
    brand: "Skin1004",
    category: "sunscreens",
    price: 1790,
    was: 2100,
    img: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800",
    images: ["https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800"],
    tag: "Bestseller",
    rating: 4.96,
    reviewCount: 320,
    volume: "50ml",
    variants: ["50ml Pump", "50ml x 2 Pack"],
    description:
      "Non-nano chemical sunscreen that blocks UV rays while simultaneously hydrating the skin. Leaves skin with a moisturized, serum-like dewy finish with zero white cast.",
    benefits: [
      "Hyalu-Cica Formula (Hyaluronic Acid + Madagascar Centella)",
      "Featherweight watery serum texture that melts in seconds",
      "Reef-safe and hypoallergenic certified",
    ],
    howToUse: "Pump 2-3 times and apply thoroughly on face, neck, and ears as final skincare step.",
    keyIngredients: [
      "Madagascar Centella Asiatica",
      "Hyaluronic Acid (Multi-weight)",
      "Baby Green Complex",
      "Niacinamide",
    ],
    skinType: ["Oily", "Acne-Prone", "Sensitive", "Combination"],
    inStock: true,
    stockCount: 50,
  },
  {
    slug: "haruharu-wonder-black-rice-moisture-airyfit-daily-sunscreen-spf50",
    name: "Haruharu Wonder Black Rice Moisture Airyfit Daily Sunscreen SPF50+ PA++++",
    brand: "Haruharu Wonder",
    category: "sunscreens",
    price: 1690,
    was: 1990,
    img: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800",
    images: ["https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800"],
    tag: "New",
    rating: 4.9,
    reviewCount: 95,
    volume: "50ml",
    variants: ["50ml (Yellow Tube)"],
    description:
      "Velvety daily sunscreen that provides high UV protection with zero greasy film or white cast. Features fermented black rice oil and heartleaf extract for antioxidant defense.",
    benefits: [
      "Soft velvet satin finish suitable under makeup",
      "Moisturizes without clogging pores or causing comedones",
      "Fragrance-free and vegan certified",
    ],
    howToUse: "Apply generously to face and neck 20 minutes prior to sun exposure.",
    keyIngredients: [
      "Fermented Black Rice Oil",
      "Heartleaf Extract",
      "Ceramide NP",
      "Adenosine",
      "Niacinamide",
    ],
    skinType: ["Combination", "Dry", "Sensitive"],
    inStock: true,
    stockCount: 30,
  },
  {
    slug: "cosrx-aloe-soothing-sun-cream-spf50",
    name: "COSRX Aloe Soothing Sun Cream SPF50+ PA+++",
    brand: "COSRX",
    category: "sunscreens",
    price: 1450,
    was: 1750,
    img: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800",
    images: ["https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800"],
    tag: "Sale",
    rating: 4.82,
    reviewCount: 310,
    volume: "50ml",
    variants: ["50ml Tube"],
    description:
      "Formulated with 5,500ppm Aloe Leaf Extract, this soothing daily sunscreen feels like a lightweight moisturizer while protecting against harsh tropical sun rays.",
    benefits: [
      "5,500ppm Aloe Leaf Extract soothes heat-stressed skin",
      "Travel-friendly compact tube for easy reapplication",
      "Absorbs fast without chalky white residue",
    ],
    howToUse: "Apply a generous layer evenly to clean face and neck every morning.",
    keyIngredients: [
      "Aloe Arborescens Leaf Extract",
      "Glycerin",
      "Silica",
      "Dipalmitoyl Hydroxyproline",
    ],
    skinType: ["Dry", "Normal", "Sun-Damaged"],
    inStock: true,
    stockCount: 42,
  },
  {
    slug: "tocobo-cotton-soft-sun-stick-spf50",
    name: "TOCOBO Cotton Soft Sun Stick SPF50+ PA++++",
    brand: "TOCOBO",
    category: "sunscreens",
    price: 1590,
    was: 1890,
    img: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800",
    images: ["https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800"],
    tag: "Hot",
    rating: 4.92,
    reviewCount: 175,
    volume: "19g",
    variants: ["19g Stick"],
    description:
      "Portable matte sun stick with Cotton Extract and AC Herb Complex that absorbs excess sebum and sweat. Glides smoothly over skin or makeup without hands.",
    benefits: [
      "Ultra-matte finish with micro-powder sebum control",
      "Mess-free portable glide stick for on-the-go reapplication",
      "Calms active inflammation with AC Herb Complex",
    ],
    howToUse:
      "Twist up bottom dial to expose 5mm of product and glide evenly across face and neck.",
    keyIngredients: ["Cotton Extract", "AC Herb Complex", "Evening Primrose Extract", "Silica"],
    skinType: ["Oily", "Sweaty", "Combination", "Acne-Prone"],
    inStock: true,
    stockCount: 38,
  },
  {
    slug: "cosrx-low-ph-good-morning-gel-cleanser",
    name: "COSRX Low pH Good Morning Gel Cleanser",
    brand: "COSRX",
    category: "cleansers",
    price: 1250,
    was: 1500,
    img: "https://images.unsplash.com/photo-1556228852-6d35a585d566?w=800",
    images: ["https://images.unsplash.com/photo-1556228852-6d35a585d566?w=800"],
    tag: "Bestseller",
    rating: 4.88,
    reviewCount: 450,
    volume: "150ml",
    variants: ["150ml Standard", "50ml Mini"],
    description:
      "Formulated with Tea Tree Oil and natural BHA to refine skin texture, this gentle morning gel cleanser maintains skin's optimal sub-acidic pH (5.0 - 6.0) without stripping moisture.",
    benefits: [
      "Slightly acidic pH 5.0 - 6.0 respects natural acid mantle",
      "Tea Tree Oil helps control breakouts and bacteria",
      "Gentle botanical foam washes away overnight sebum",
    ],
    howToUse: "Lather a dime-sized amount with lukewarm water, massage onto face, and rinse well.",
    keyIngredients: [
      "0.5% Betaine Salicylate (BHA)",
      "Tea Tree Leaf Oil",
      "Cedar Leaf Extract",
      "Allantoin",
    ],
    skinType: ["All Skin Types", "Sensitive", "Acne-Prone"],
    inStock: true,
    stockCount: 55,
  },
  {
    slug: "anua-heartleaf-pore-control-cleansing-oil",
    name: "Anua Heartleaf Pore Control Cleansing Oil",
    brand: "Anua",
    category: "cleansers",
    price: 2100,
    was: 2450,
    img: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800",
    images: ["https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800"],
    tag: "Bestseller",
    rating: 4.95,
    reviewCount: 380,
    volume: "200ml",
    variants: ["200ml Pump"],
    description:
      "TikTok viral pore-clearing oil cleanser that melts waterproof makeup, stubborn blackheads, and sebum plugs with Heartleaf Extract and non-comedogenic plant oils.",
    benefits: [
      "Melt blackheads and sunscreen effortlessly",
      "Heartleaf extract calms redness during deep cleansing",
      "Emulsifies instantly into a light milk with water",
    ],
    howToUse: "Massage 2-3 pumps onto dry skin for 1 minute, add water to emulsify, then rinse.",
    keyIngredients: [
      "Heartleaf Extract (Houttuynia Cordata)",
      "Jojoba Seed Oil",
      "Olive Fruit Oil",
      "Grape Seed Oil",
    ],
    skinType: ["Blackhead-Prone", "Clogged Pores", "Acne-Prone", "Oily"],
    inStock: true,
    stockCount: 40,
  },
  {
    slug: "beauty-of-joseon-green-plum-refreshing-cleanser",
    name: "Beauty of Joseon Green Plum Refreshing Cleanser",
    brand: "Beauty of Joseon",
    category: "cleansers",
    price: 1450,
    was: 1750,
    img: "https://images.unsplash.com/photo-1556228852-6d35a585d566?w=800",
    images: ["https://images.unsplash.com/photo-1556228852-6d35a585d566?w=800"],
    tag: "New",
    rating: 4.87,
    reviewCount: 165,
    volume: "100ml",
    variants: ["100ml Tube"],
    description:
      "Hypoallergenic low pH gel cleanser formulated with Green Plum Water and Mung Bean Seed Extract to gently lift dead skin cells while leaving skin hydrated and calm.",
    benefits: [
      "Naturally derived fruit acids from Plum gently soften keratin",
      "Mung bean extracts protect skin barrier",
      "Bouncy gel texture creates plush micro-bubbles",
    ],
    howToUse:
      "Apply appropriate amount onto wet hands, lather well, and gently massage across face.",
    keyIngredients: [
      "Green Plum Water (24%)",
      "Mung Bean Seed Extract (3%)",
      "Lotus Flower Extract",
    ],
    skinType: ["Dry", "Sensitive", "Combination"],
    inStock: true,
    stockCount: 30,
  },
  {
    slug: "skin1004-madagascar-centella-light-cleansing-oil",
    name: "Skin1004 Madagascar Centella Light Cleansing Oil",
    brand: "Skin1004",
    category: "cleansers",
    price: 1950,
    was: 2300,
    img: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800",
    images: ["https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800"],
    tag: "Bestseller",
    rating: 4.91,
    reviewCount: 210,
    volume: "200ml",
    variants: ["200ml"],
    description:
      "All-in-one non-comedogenic cleansing oil made with Centella oil extract from Madagascar and 6 botanical oils that easily dissolves heavy makeup without stinging eyes.",
    benefits: [
      "Featherlight oil that rinses completely clean without residue",
      "Safe for sensitive eyes and contact lens wearers",
      "Soothes skin with pure Centella Asiatica",
    ],
    howToUse:
      "Pump onto dry hands and massage over dry face. Wet face to emulsify and rinse thoroughly.",
    keyIngredients: [
      "Madagascar Centella Oil Extract",
      "Bergamot Fruit Oil",
      "Sunflower Seed Oil",
      "Jojoba Oil",
    ],
    skinType: ["Sensitive", "All Skin Types", "Dry"],
    inStock: true,
    stockCount: 35,
  },
  {
    slug: "round-lab-1025-dokdo-cleanser",
    name: "Round Lab 1025 Dokdo Cleanser",
    brand: "Round Lab",
    category: "cleansers",
    price: 1390,
    was: 1650,
    img: "https://images.unsplash.com/photo-1556228852-6d35a585d566?w=800",
    images: ["https://images.unsplash.com/photo-1556228852-6d35a585d566?w=800"],
    tag: "Sale",
    rating: 4.89,
    reviewCount: 190,
    volume: "150ml",
    variants: ["150ml"],
    description:
      "Slightly acidic (pH 5.0 - 6.0) dense foaming cleanser with Ulleungdo deep sea water that effectively cleanses ultra-fine dust and impurities without stripping moisture.",
    benefits: [
      "Dense, creamy foam creates gentle cushion between hands and skin",
      "Triple Hyaluronic Acid locks in moisture post-wash",
      "Clinically proven fine-dust cleansing power",
    ],
    howToUse:
      "Create a rich lather with small amount of water, gently massage, and rinse with lukewarm water.",
    keyIngredients: [
      "Deep Sea Water",
      "Triple Hyaluronic Acid",
      "Panthenol",
      "Allantoin",
      "Ceramide NP",
    ],
    skinType: ["Sensitive", "Normal", "Dry"],
    inStock: true,
    stockCount: 25,
  },
  {
    slug: "banila-co-clean-it-zero-original-cleansing-balm",
    name: "Banila Co Clean It Zero Original Cleansing Balm",
    brand: "Banila Co",
    category: "cleansers",
    price: 1890,
    was: 2200,
    img: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800",
    images: ["https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800"],
    tag: "Bestseller",
    rating: 4.94,
    reviewCount: 520,
    volume: "100ml",
    variants: ["100ml Tub", "180ml Jumbo"],
    description:
      "World-famous sherbet-like cleansing balm that transforms into a smooth oil upon skin contact. Melts away stubborn waterproof mascara, long-wear foundation, and sunscreen.",
    benefits: [
      "Zero Drip sherbet formula makes makeup removal mess-free",
      "Hot Spring Water and Acerola Extract keep skin hydrated",
      "Hypoallergenic and non-irritating to sensitive eyes",
    ],
    howToUse:
      "Use spatula to scoop a coin-sized amount. Massage in circular motions and rinse clean.",
    keyIngredients: [
      "Acerola Fruit Extract",
      "Rooibos Leaf Extract",
      "Bamboo Extract",
      "Hot Spring Water",
    ],
    skinType: ["All Skin Types", "Heavy Makeup Wearers"],
    inStock: true,
    stockCount: 42,
  },
  {
    slug: "cosrx-advanced-snail-92-all-in-one-cream",
    name: "COSRX Advanced Snail 92 All In One Cream",
    brand: "COSRX",
    category: "moisturizers",
    price: 1850,
    was: 2200,
    img: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800",
    images: [
      "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800",
      "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800",
    ],
    tag: "Bestseller",
    rating: 4.91,
    reviewCount: 390,
    volume: "100g",
    variants: ["100g Tub", "100g Tube"],
    description:
      "Enriched with 92% pure Snail Secretion Filtrate, this lightweight gel-cream glides onto skin to build a moisture shield while plumping fine lines and soothing post-breakout scars.",
    benefits: [
      "92% Snail Secretion Filtrate for intense cellular recovery",
      "Bouncy gel texture delivers instant cool hydration",
      "Fades blemishes and calms inflamed irritated patches",
    ],
    howToUse: "Gently apply a proper amount to face after serum, tapping until fully absorbed.",
    keyIngredients: [
      "92% Snail Secretion Filtrate",
      "Sodium Hyaluronate",
      "Panthenol",
      "Allantoin",
      "Adenosine",
    ],
    skinType: ["Acne-Prone", "Combination", "Oily", "Sensitive"],
    inStock: true,
    stockCount: 50,
  },
  {
    slug: "illiyoon-ceramide-ato-concentrate-cream",
    name: "Illiyoon Ceramide Ato Concentrate Cream",
    brand: "Illiyoon",
    category: "moisturizers",
    price: 1950,
    was: 2350,
    img: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800",
    images: ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800"],
    tag: "Bestseller",
    rating: 4.96,
    reviewCount: 460,
    volume: "200ml",
    variants: ["200ml Tube", "500ml Tub"],
    description:
      "Korea's #1 barrier recovery cream containing patented Ceramide Skin Complex capsules that burst upon application to immediately mend damaged, peeling, and sensitized skin barriers.",
    benefits: [
      "Patented Ceramide Capsules deeply fortify compromised barrier",
      "Clinically proven 100-hour continuous moisture retention",
      "0% Paraben, fragrance, mineral oil, or synthetic color",
    ],
    howToUse: "Apply generously to dry, compromised areas on face and body as needed.",
    keyIngredients: [
      "Ceramide NP (Encapsulated)",
      "Phytosphingosine",
      "Panax Ginseng Root Water",
      "Soybean Ferment Extract",
    ],
    skinType: ["Extremely Dry", "Eczema-Prone", "Damaged Barrier", "Sensitive"],
    inStock: true,
    stockCount: 44,
  },
  {
    slug: "beauty-of-joseon-dynasty-cream",
    name: "Beauty of Joseon Dynasty Cream",
    brand: "Beauty of Joseon",
    category: "moisturizers",
    price: 1890,
    was: 2250,
    img: "https://images.unsplash.com/photo-1617897903246-719242758050?w=800",
    images: ["https://images.unsplash.com/photo-1617897903246-719242758050?w=800"],
    tag: "Bestseller",
    rating: 4.88,
    reviewCount: 280,
    volume: "50ml",
    variants: ["50ml Jar"],
    description:
      "Luxurious Hanbang moisture cream enriched with 29% Rice Bran Water, 5% Ginseng Root Water, 2% Niacinamide, and 3% Squalane to bestow a radiant, bouncy glow fit for Joseon royalty.",
    benefits: [
      "Traditional Korean Hanbang medicinal ingredients nourish deeply",
      "Unique slightly stringy texture locks moisture without heaviness",
      "Promotes firmer skin elasticity and natural luminosity",
    ],
    howToUse: "Smooth an appropriate amount over face and neck as the last step of night routine.",
    keyIngredients: [
      "Rice Bran Water (29%)",
      "Ginseng Root Water (5%)",
      "Squalane (3%)",
      "Niacinamide (2%)",
      "Ceramide NP",
    ],
    skinType: ["Normal", "Dry", "Aging", "Combination"],
    inStock: true,
    stockCount: 36,
  },
  {
    slug: "round-lab-birch-juice-moisturizing-cream",
    name: "Round Lab Birch Juice Moisturizing Cream",
    brand: "Round Lab",
    category: "moisturizers",
    price: 1990,
    was: 2400,
    img: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800",
    images: ["https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800"],
    tag: "New",
    rating: 4.9,
    reviewCount: 140,
    volume: "80ml",
    variants: ["80ml Jar"],
    description:
      "Refreshing moisture cream packed with Inje Silver Birch Tree Sap and Moisture Capsule Beads that burst with hydration, delivering a 48-hour cooling hydration veil.",
    benefits: [
      "Collagen moisture capsules burst on contact to quench dehydration",
      "Purifying birch sap purges skin dullness",
      "Zero sticky residue — perfect for humid Bangladesh summers",
    ],
    howToUse: "Apply moderate amount across face and gently press with palms for absorption.",
    keyIngredients: [
      "Inje Birch Sap (10,000ppm)",
      "Vita Hyaluronic Acid",
      "Turmeric Root Extract",
      "Moringa Oleifera Seed Oil",
    ],
    skinType: ["Dehydrated", "Oily-Dehydrated", "Combination"],
    inStock: true,
    stockCount: 28,
  },
  {
    slug: "torriden-dive-in-soothing-cream",
    name: "Torriden DIVE-IN Low Molecular Hyaluronic Acid Soothing Cream",
    brand: "Torriden",
    category: "moisturizers",
    price: 1890,
    was: 2200,
    img: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800",
    images: ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800"],
    tag: "Sale",
    rating: 4.92,
    reviewCount: 195,
    volume: "100ml",
    variants: ["100ml Tub"],
    description:
      "Featherlight pastel-blue water gel cream packed with 5D Hyaluronic Acid and Trehalose that instantly lowers skin temperature and calms sensitized red skin.",
    benefits: [
      "Instantly cools and relieves overheated, flushed skin",
      "Watery gel absorbs in under 10 seconds with 0% greasiness",
      "Provides long-lasting core hydration for acne-prone skin",
    ],
    howToUse: "Spread generously over face. Can also be used as a cooling sleeping mask.",
    keyIngredients: [
      "5D-Complex Hyaluronic Acid",
      "Trehalose",
      "Blue Complex (6 Herbal Extracts)",
      "Allantoin",
    ],
    skinType: ["Oily", "Acne-Prone", "Heated Skin", "Combination"],
    inStock: true,
    stockCount: 32,
  },
  {
    slug: "etude-house-soonjung-2x-barrier-intensive-cream",
    name: "ETUDE SoonJung 2x Barrier Intensive Cream",
    brand: "ETUDE",
    category: "moisturizers",
    price: 1750,
    was: 2100,
    img: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800",
    images: ["https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800"],
    tag: "Bestseller",
    rating: 4.93,
    reviewCount: 310,
    volume: "60ml",
    variants: ["60ml Twist Tube"],
    description:
      "A soothing cream with Panthenoside (Panthenol + Madecassoside) and 93% naturally derived ingredients that repairs the protein barrier and balances oil-water levels.",
    benefits: [
      "Panthenol strengthens skin barrier and calms stress",
      "Madecassoside repairs irritated and acne-damaged skin",
      "Clean 10-Free hypoallergenic formula with rotary lock cap",
    ],
    howToUse:
      "Rotate cap counter-clockwise to open, squeeze a pea-sized amount, and massage onto skin.",
    keyIngredients: [
      "Panthenol (Vitamin B5)",
      "Madecassoside",
      "Shea Butter",
      "Sunflower Seed Oil",
    ],
    skinType: ["Ultra-Sensitive", "Irritated", "Dry", "Damaged Barrier"],
    inStock: true,
    stockCount: 38,
  },
  {
    slug: "mediheal-nmf-aquaring-ampoule-mask-ex",
    name: "Mediheal N.M.F Aquaring Ampoule Sheet Mask EX (Box of 10)",
    brand: "Mediheal",
    category: "masks",
    price: 1990,
    was: 2400,
    img: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800",
    images: ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800"],
    tag: "Bestseller",
    rating: 4.97,
    reviewCount: 410,
    volume: "10 Sheets Box",
    variants: ["Box of 10", "Single Sheet (৳220)"],
    description:
      "World #1 sheet mask with over 2 billion sheets sold worldwide. Infused with Natural Moisturizing Factors (N.M.F), Sodium Hyaluronate, and Witch Hazel to instantly transform parched skin into a glowing glass surface.",
    benefits: [
      "Instant glass skin radiance in 15 minutes",
      "Silk-touch bamboo cellulose sheet fits skin like a second layer",
      "Tightens pores while saturating deep moisture",
    ],
    howToUse:
      "Fit mask over cleansed face for 15-20 minutes. Remove and pat remaining ampoule into skin.",
    keyIngredients: [
      "N.M.F Complex",
      "Hyaluronic Acid",
      "Witch Hazel Water",
      "Allantoin",
      "Adenosine",
    ],
    skinType: ["All Skin Types", "Dry", "Dehydrated", "Event Prep"],
    inStock: true,
    stockCount: 50,
  },
  {
    slug: "beauty-of-joseon-red-bean-refreshing-pore-mask",
    name: "Beauty of Joseon Red Bean Refreshing Pore Mask",
    brand: "Beauty of Joseon",
    category: "masks",
    price: 1750,
    was: 2050,
    img: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800",
    images: ["https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800"],
    tag: "Bestseller",
    rating: 4.88,
    reviewCount: 165,
    volume: "140ml",
    variants: ["140ml Jar"],
    description:
      "Cooling soft clay mask containing 30% Haenam Red Bean Extract and Kaolin clay that minimizes large pores and absorbs excess sebum without excessive dryness.",
    benefits: [
      "30% Red Bean Extract & Kaolin clay unclog stubborn sebum",
      "Gentle red bean scrub particles buff away dead keratin",
      "Leaves skin clear, cool, and refreshed",
    ],
    howToUse:
      "Spread evenly on dry face, leave on for 10-15 minutes, then rinse off gently with lukewarm water.",
    keyIngredients: [
      "Haenam Red Bean Extract (30%)",
      "Kaolin Clay",
      "Pear Fruit Extract",
      "Strawberry Fruit Extract",
    ],
    skinType: ["Oily", "Large Pores", "Blackheads", "Congested"],
    inStock: true,
    stockCount: 25,
  },
  {
    slug: "im-from-mugwort-mask",
    name: "I'm From Mugwort Calming Wash-Off Mask",
    brand: "I'm From",
    category: "masks",
    price: 2250,
    was: 2600,
    img: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800",
    images: ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800"],
    tag: "New",
    rating: 4.93,
    reviewCount: 190,
    volume: "110g",
    variants: ["110g Jar", "30g Mini"],
    description:
      "A premium soothing wash-off mask containing 2.1% real Ganghwa Mugwort powder that calms hot, irritated skin, detoxifies blemishes, and cools redness instantly.",
    benefits: [
      "2.1% Pure Ganghwa Mugwort powder soothes inflammation",
      "Gel texture full of herbal extracts reduces skin heat",
      "Detoxifies and clarifies troubled, acne-prone complexion",
    ],
    howToUse:
      "Apply a generous layer over clean face, relax for 10-15 minutes, and rinse with warm water.",
    keyIngredients: [
      "2.1% Ganghwa Mugwort Powder",
      "Centella Asiatica",
      "Cordyceps Sinensis",
      "Licorice Extract",
    ],
    skinType: ["Inflamed Acne", "Sensitive", "Overheated", "Irritated"],
    inStock: true,
    stockCount: 20,
  },
  {
    slug: "anua-heartleaf-77-soothing-sheet-mask-set",
    name: "Anua Heartleaf 77% Soothing Sheet Mask (Set of 5)",
    brand: "Anua",
    category: "masks",
    price: 1450,
    was: 1750,
    img: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800",
    images: ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800"],
    tag: "Bestseller",
    rating: 4.91,
    reviewCount: 130,
    volume: "5 Sheets Pack",
    variants: ["5 Sheets Pack"],
    description:
      "Drenched in a whole bottle of Anua 77% Heartleaf essence, these micro-fiber soothing sheets hug facial contours tightly to extinguish redness and irritation.",
    benefits: [
      "Packed with 77% Korean Heartleaf extract in every single pouch",
      "Rapid relief from sun exposure, heat redness, and sudden breakouts",
      "Ultra-fine vegan micro-fiber sheet",
    ],
    howToUse:
      "Smooth mask over face after cleansing, leave for 15 minutes, and tap excess serum into neck.",
    keyIngredients: [
      "Heartleaf Extract (77%)",
      "Centella Asiatica",
      "Panthenol",
      "Hyaluronic Acid",
    ],
    skinType: ["Acne-Prone", "Irritated", "Sensitive", "Redness"],
    inStock: true,
    stockCount: 30,
  },
  {
    slug: "some-by-mi-real-tea-tree-calming-care-mask-set",
    name: "Some By Mi Real Tea Tree Calming Care Sheet Mask (Set of 5)",
    brand: "Some By Mi",
    category: "masks",
    price: 1350,
    was: 1600,
    img: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800",
    images: ["https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800"],
    tag: "Sale",
    rating: 4.85,
    reviewCount: 95,
    volume: "5 Sheets Pack",
    variants: ["5 Sheets Pack"],
    description:
      "Real botanical essence sheet mask with Tea Tree Extract that soothes skin trouble, clears sebum, and provides refreshing hydration to blemish-prone complexions.",
    benefits: [
      "Natural Tea Tree Extract cleanses impurities and calms zits",
      "100% plant-based biodegradable cellulose sheet",
      "Fresh cooling sensation on irritated skin",
    ],
    howToUse: "Apply mask evenly onto face, leave on for 15-20 minutes, then discard and pat skin.",
    keyIngredients: [
      "Tea Tree Leaf Extract",
      "Allantoin",
      "Coptis Japonica Root Extract",
      "Glycerin",
    ],
    skinType: ["Blemish-Prone", "Oily", "Acne-Prone"],
    inStock: true,
    stockCount: 35,
  },
  {
    slug: "skin1004-madagascar-centella-watergel-sheet-ampoule-mask-set",
    name: "Skin1004 Madagascar Centella Watergel Sheet Ampoule Mask (Set of 5)",
    brand: "Skin1004",
    category: "masks",
    price: 1490,
    was: 1790,
    img: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800",
    images: ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800"],
    tag: "New",
    rating: 4.94,
    reviewCount: 110,
    volume: "5 Sheets Pack",
    variants: ["5 Sheets Pack"],
    description:
      "Watergel sheet mask made with Centella Asiatica that holds 3x more ampoule than regular sheets. Delivers rapid barrier relief and a deep soothing surge.",
    benefits: [
      "Holds 300% more moisture with unique Centella-woven watergel fabric",
      "Provides intensive barrier repair and calming care",
      "100% pure Madagascar Centella formula",
    ],
    howToUse: "Place mask on face for 10-20 minutes. Pat remaining ampoule until absorbed.",
    keyIngredients: [
      "Madagascar Centella Asiatica Extract (51%)",
      "Cornmint Oil",
      "Hyaluronic Acid",
      "Betaine",
    ],
    skinType: ["Sensitive", "Flushed", "Dehydrated"],
    inStock: true,
    stockCount: 28,
  },
  {
    slug: "laneige-lip-sleeping-mask-berry",
    name: "Laneige Lip Sleeping Mask (Berry)",
    brand: "Laneige",
    category: "eye-lip-care",
    price: 1690,
    was: 1990,
    img: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800",
    images: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800"],
    tag: "Bestseller",
    rating: 4.96,
    reviewCount: 512,
    volume: "20g",
    variants: ["20g (Full Size)", "8g (Mini)"],
    description:
      "A leave-on lip mask that soothes and moisturizes for smoother, more supple lips overnight. Proprietary Berry Fruit Complex with Vitamin C and rich antioxidants melts dead skin cells, giving you baby-soft, plumper lips by morning.",
    benefits: [
      "Dissolves stubborn flaky dead skin overnight",
      "Infused with Vitamin C and powerful berry antioxidants",
      "Moisture Wrap technology locks in moisture for 8 continuous hours",
      "Delicious sweet berry aroma",
    ],
    howToUse:
      "Before going to bed at night, apply an adequate amount on the lips using the included spatula. The next morning, gently wipe the lips clean with a tissue or cotton pad.",
    keyIngredients: [
      "Berry Fruit Complex",
      "Vitamin C",
      "Coconut Oil",
      "Shea Butter",
      "Murumuru Seed Butter",
    ],
    skinType: ["Chapped Lips", "Dry Lips", "All Skin Types"],
    inStock: true,
    stockCount: 40,
  },
  {
    slug: "beauty-of-joseon-revive-eye-serum-ginseng-retinal",
    name: "Beauty of Joseon Revive Eye Serum : Ginseng + Retinal",
    brand: "Beauty of Joseon",
    category: "eye-lip-care",
    price: 1790,
    was: 2150,
    img: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800",
    images: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800"],
    tag: "Bestseller",
    rating: 4.94,
    reviewCount: 340,
    volume: "30ml",
    variants: ["30ml Pump"],
    description:
      "Silky anti-aging eye serum combining 10% Ginseng Root Extract and 2% Retinal Liposome to visibly improve under-eye wrinkles, crow's feet, and dark circles with zero irritation.",
    benefits: [
      "2% Stabilized Retinal Liposome converts 11x faster than retinol",
      "10% Ginseng Extract promotes circulation and elasticity",
      "Silky serum texture doesn't cause milia seeds",
    ],
    howToUse:
      "Dispense 1 pump and gently pat around eye orbital bone using ring finger every evening.",
    keyIngredients: [
      "Ginseng Root Extract (10%)",
      "Retinal Liposome (2%)",
      "Niacinamide",
      "Macadamia Seed Oil",
      "Cholesterol",
    ],
    skinType: ["Fine Lines", "Dark Circles", "Aging Under-Eyes"],
    inStock: true,
    stockCount: 45,
  },
  {
    slug: "cosrx-advanced-snail-peptide-eye-cream",
    name: "COSRX Advanced Snail Peptide Eye Cream",
    brand: "COSRX",
    category: "eye-lip-care",
    price: 2150,
    was: 2550,
    img: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800",
    images: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800"],
    tag: "Bestseller",
    rating: 4.9,
    reviewCount: 220,
    volume: "25ml",
    variants: ["25ml Pump"],
    description:
      "Double-action eye cream containing 72% Snail Secretion Filtrate and 5 Peptides Complex to brighten dark under-eye shadow, depuff morning bags, and firm delicate eye skin.",
    benefits: [
      "72% Snail Mucin hydrates and firms slackened eye contours",
      "5 Peptide Complex boosts collagen synthesis",
      "Niacinamide brightens dull under-eye shadows",
    ],
    howToUse: "Apply around eyes and gently pat with fingertips for maximum absorption.",
    keyIngredients: [
      "72% Snail Secretion Filtrate",
      "5 Peptides Complex",
      "Niacinamide",
      "Copper Tripeptide-1",
      "Hyaluronic Acid",
    ],
    skinType: ["Dark Circles", "Puffy Eyes", "All Skin Types"],
    inStock: true,
    stockCount: 30,
  },
  {
    slug: "haruharu-wonder-black-rice-bakuchiol-eye-cream",
    name: "Haruharu Wonder Black Rice Bakuchiol Eye Cream",
    brand: "Haruharu Wonder",
    category: "eye-lip-care",
    price: 1850,
    was: 2200,
    img: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800",
    images: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800"],
    tag: "New",
    rating: 4.89,
    reviewCount: 105,
    volume: "20ml",
    variants: ["20ml Tube"],
    description:
      "Plant-based retinol alternative eye cream powered by 5,000ppm natural Bakuchiol and fermented black rice to firm wrinkles without causing irritation or sun sensitivity.",
    benefits: [
      "Natural Bakuchiol firms fine lines safely day and night",
      "Fermented Black Rice offers high antioxidant nourishment",
      "Lightweight milky texture absorbs instantly",
    ],
    howToUse: "Tap gently around the eye area morning and night.",
    keyIngredients: [
      "Bakuchiol (5,000ppm)",
      "Fermented Black Rice Extract",
      "Bamboo Shoot Bark Extract",
      "Natatto Gum",
    ],
    skinType: ["Sensitive Eyes", "Fine Lines", "Dry Under-Eyes"],
    inStock: true,
    stockCount: 26,
  },
  {
    slug: "laneige-lip-glowy-balm-berry",
    name: "Laneige Lip Glowy Balm (Berry)",
    brand: "Laneige",
    category: "eye-lip-care",
    price: 1250,
    was: 1500,
    img: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800",
    images: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800"],
    tag: "Sale",
    rating: 4.93,
    reviewCount: 260,
    volume: "10g",
    variants: ["10g Squeeze Tube"],
    description:
      "The daytime companion to the Lip Sleeping Mask. Delivers glossy shine and intense moisture with Shea Butter and Murumuru Butter in an easy pocket squeeze tube.",
    benefits: [
      "Pocket-sized gloss balm for daytime hydration",
      "Natural berry tint and mirror-like shine",
      "Locks moisture with Shea and Murumuru butters",
    ],
    howToUse: "Apply directly to lips whenever dry or as a glossy lip topper.",
    keyIngredients: ["Shea Butter", "Murumuru Seed Butter", "Berry Complex", "Vitamin C"],
    skinType: ["Dry Lips", "Everyday Use"],
    inStock: true,
    stockCount: 45,
  },
  {
    slug: "torriden-solid-in-ceramide-lip-essence",
    name: "Torriden Solid-In Ceramide Lip Essence",
    brand: "Torriden",
    category: "eye-lip-care",
    price: 990,
    was: 1250,
    img: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800",
    images: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800"],
    tag: "Hot",
    rating: 4.95,
    reviewCount: 310,
    volume: "11ml",
    variants: ["11ml Tube"],
    description:
      "Olive Young #1 Lip Care Winner. Formulated with 5D Ceramide Complex and Organic Jojoba Oil that instantly heals severely cracked, peeling, and bleeding lips.",
    benefits: [
      "5D Ceramide Complex repairs damaged lip moisture barriers",
      "Jojoba Oil gently softens stubborn dead skin flakes",
      "Thick nourishing essence with zero sticky heaviness",
    ],
    howToUse: "Squeeze a moderate amount and spread over dry, chapped lips.",
    keyIngredients: ["5D Ceramide Complex", "Jojoba Seed Oil (5%)", "Shea Butter", "Trehalose"],
    skinType: ["Severely Chapped Lips", "Cracked Lips"],
    inStock: true,
    stockCount: 60,
  },
  {
    slug: "cosrx-all-about-snail-4-step-skincare-starter-kit",
    name: "COSRX All About Snail 4-Step Skincare Starter Kit",
    brand: "COSRX",
    category: "sets",
    price: 2450,
    was: 2950,
    img: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800",
    images: [
      "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800",
      "https://images.unsplash.com/photo-1576426863848-c21f53c60b19?w=800",
    ],
    tag: "Bestseller",
    rating: 4.97,
    reviewCount: 320,
    volume: "4-Piece Set",
    variants: ["Full Kit Box"],
    description:
      "Complete 4-step snail mucin routine box containing: Snail Cleanser (20ml), Snail 96 Mucin Essence (30ml), Snail Peptide Eye Cream (5g), and Snail 92 All in One Cream (20g).",
    benefits: [
      "Complete daily Korean repair routine in one luxury travel box",
      "Fades dark spots, locks hydration, and firms eye contours",
      "Ideal gift for beginners and skincare enthusiasts",
    ],
    howToUse:
      "Follow the 4 steps morning and night: Cleanser -> Essence -> Eye Cream -> All in One Cream.",
    keyIngredients: [
      "Snail Secretion Filtrate (96% & 92%)",
      "5 Peptides",
      "Niacinamide",
      "Hyaluronic Acid",
    ],
    skinType: ["All Skin Types", "Damaged Barrier", "Travel"],
    inStock: true,
    stockCount: 35,
  },
  {
    slug: "beauty-of-joseon-hanbang-trio-serum-discovery-set",
    name: "Beauty of Joseon Hanbang Trio Serum Discovery Set",
    brand: "Beauty of Joseon",
    category: "sets",
    price: 2650,
    was: 3200,
    img: "https://images.unsplash.com/photo-1576426863848-c21f53c60b19?w=800",
    images: ["https://images.unsplash.com/photo-1576426863848-c21f53c60b19?w=800"],
    tag: "Bestseller",
    rating: 4.95,
    reviewCount: 280,
    volume: "3 x 30ml Serums",
    variants: ["3-Pack Serum Set"],
    description:
      "Trio box containing full sizes of BOJ's top three serums: Glow Serum (Propolis + Niacinamide), Glow Deep Serum (Rice + Arbutin), and Revive Serum (Ginseng + Snail Mucin).",
    benefits: [
      "Target all skin concerns: breakouts, dark spots, and anti-aging",
      "Traditional Hanbang herbal wisdom combined with modern actives",
      "Great value bundle saving ৳1,500 compared to individual purchases",
    ],
    howToUse: "Use Glow Deep Serum in morning and alternate Glow / Revive Serums at night.",
    keyIngredients: [
      "Propolis",
      "Niacinamide",
      "Rice Bran Water",
      "Alpha-Arbutin",
      "Ginseng",
      "Snail Mucin",
    ],
    skinType: ["All Skin Types", "Dull", "Pigmented", "Acne-Prone"],
    inStock: true,
    stockCount: 28,
  },
  {
    slug: "anua-heartleaf-calming-routine-trio",
    name: "Anua Heartleaf Soothing & Barrier Trio Set",
    brand: "Anua",
    category: "sets",
    price: 4850,
    was: 5800,
    img: "https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?w=800",
    images: ["https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?w=800"],
    tag: "New",
    rating: 4.92,
    reviewCount: 140,
    volume: "3 Full Size Products",
    variants: ["Full Routine Trio"],
    description:
      "The definitive acne-calming routine: Heartleaf Pore Cleansing Oil (200ml) + Heartleaf 77% Toner (250ml) + Heartleaf Daily Moisture Lotion (200ml).",
    benefits: [
      "Complete 3-step solution to banish fungal acne and clogged pores",
      "Restores sub-acidic pH balance and stops excess sebum",
      "100% genuine Olive Young award-winning lineup",
    ],
    howToUse: "Step 1: Cleansing Oil -> Step 2: 77% Toner -> Step 3: Moisture Lotion.",
    keyIngredients: [
      "Heartleaf Extract (77%)",
      "Jojoba Oil",
      "Panthenol",
      "Centella Asiatica",
      "Hyaluronic Acid",
    ],
    skinType: ["Acne-Prone", "Fungal Acne", "Sensitive", "Oily"],
    inStock: true,
    stockCount: 22,
  },
  {
    slug: "round-lab-1025-dokdo-hydration-essentials-set",
    name: "Round Lab 1025 Dokdo Hydration Essentials Set",
    brand: "Round Lab",
    category: "sets",
    price: 3950,
    was: 4700,
    img: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800",
    images: ["https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800"],
    tag: "Sale",
    rating: 4.9,
    reviewCount: 160,
    volume: "Toner + Cleanser + Lotion",
    variants: ["Full Set"],
    description:
      "Clean beauty trio from Korea's clean island: Dokdo Cleanser (150ml) + Dokdo Exfoliating Toner (200ml) + Dokdo Hydrating Lotion (200ml).",
    benefits: [
      "Powered by 74 deep ocean minerals for supple resilient skin",
      "Gentle daily enzyme exfoliation without physical scrubbing",
      "Soothes sensitive, rough, and sun-stressed skin textures",
    ],
    howToUse: "Use morning and night: Cleanser -> Toner -> Lotion.",
    keyIngredients: [
      "Ulleungdo Deep Ocean Minerals",
      "Hatching EX-07",
      "Triple Hyaluronic Acid",
      "Panthenol",
    ],
    skinType: ["Sensitive", "Dry", "Rough Texture", "Normal"],
    inStock: true,
    stockCount: 20,
  },
  {
    slug: "skin1004-madagascar-centella-soothing-travel-kit",
    name: "Skin1004 Madagascar Centella Soothing Travel Kit (5-Piece)",
    brand: "Skin1004",
    category: "sets",
    price: 2250,
    was: 2700,
    img: "https://images.unsplash.com/photo-1576426863848-c21f53c60b19?w=800",
    images: ["https://images.unsplash.com/photo-1576426863848-c21f53c60b19?w=800"],
    tag: "Hot",
    rating: 4.96,
    reviewCount: 210,
    volume: "5 Deluxe Minis",
    variants: ["Travel Pouch Included"],
    description:
      "Deluxe 5-piece travel kit: Cleansing Oil (30ml) + Ampoule Foam (20ml) + Toning Toner (30ml) + Centella Ampoule (30ml) + Soothing Cream (30ml) inside a chic waterproof pouch.",
    benefits: [
      "Full 5-step Korean skincare ritual in TSA-approved travel sizes",
      "Heals skin breakouts and barrier damage while on flights or vacations",
      "Includes premium frosted travel pouch",
    ],
    howToUse: "Follow the 5 steps morning and evening during travel or everyday routine.",
    keyIngredients: [
      "Madagascar Centella Asiatica",
      "PHA (Gluconolactone)",
      "Hyaluronic Acid",
      "Ceramides",
    ],
    skinType: ["Sensitive", "Acne-Prone", "Travelers"],
    inStock: true,
    stockCount: 30,
  },
  {
    slug: "ultimate-5-step-korean-glass-skin-daily-ritual-box",
    name: "Ultimate 5-Step Korean Glass Skin Daily Ritual Box",
    brand: "KoreanSkincare.bd Curated",
    category: "sets",
    price: 6450,
    was: 7800,
    img: "https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?w=800",
    images: [
      "https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?w=800",
      "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800",
    ],
    tag: "Limited",
    rating: 4.99,
    reviewCount: 180,
    volume: "5 Full Sized Holy Grails",
    variants: ["Curated Luxury Box"],
    description:
      "Our most prestigious curated collection: COSRX Snail Cleanser + Anua 77% Toner + AXIS-Y Glow Serum + Beauty of Joseon Dynasty Cream + BOJ Rice Sunscreen SPF50+ in a presentation gift box.",
    benefits: [
      "Guaranteed genuine Seoul cult favorites bundled at an incredible savings",
      "The complete 5-step roadmap to radiant Korean glass skin",
      "Includes complimentary silk headband and step-by-step routine guide",
    ],
    howToUse:
      "Step 1: Cleanser -> Step 2: Toner -> Step 3: Serum -> Step 4: Cream -> Step 5: SPF (Morning).",
    keyIngredients: [
      "Snail Mucin",
      "Heartleaf (77%)",
      "Niacinamide (5%)",
      "Rice Extract (30%)",
      "Ginseng",
    ],
    skinType: ["All Skin Types", "Glass Skin Seekers", "Luxury Gifting"],
    inStock: true,
    stockCount: 15,
  },

  // ─── LUXURY ACCESSORIES & BAGS ───
  {
    slug: "blush-mini-crossbody",
    name: "Blush Mini Crossbody Luxury Bag",
    brand: "koreanskincare.bd Luxe",
    category: "bags",
    price: 3490,
    was: 4200,
    img: catBags,
    tag: "New",
    rating: 4.85,
    reviewCount: 94,
    volume: "Standard Bag",
    variants: ["Blush Pink", "Noir Black", "Ivory Cream"],
    description:
      "Handcrafted with premium vegan leather, gold-tone hardware, and versatile shoulder strap for elegant modern styling.",
    benefits: [
      "Scratch-resistant vegan leather",
      "Signature gold metal lock",
      "Compact multi-pocket interior",
    ],
    howToUse: "Wear crossbody or unclip strap for an evening clutch look.",
    keyIngredients: ["Premium Microfiber Vegan Leather", "Gold Hardware"],
    skinType: ["Accessories"],
    inStock: true,
    stockCount: 18,
  },
  {
    slug: "beige-woven-tote",
    name: "Beige Woven Artisan Tote",
    brand: "koreanskincare.bd Luxe",
    category: "bags",
    price: 4290,
    was: null,
    img: prBag1,
    tag: "Bestseller",
    rating: 4.9,
    reviewCount: 110,
    volume: "Large Tote",
    variants: ["Natural Beige", "Mocha Brown"],
    description:
      "Spacious luxury woven tote tailored for city commutes, laptop carriage, and effortless weekend escapes.",
    benefits: [
      "Fits 14-inch laptops",
      "Reinforced double handles",
      "Zippered security compartment",
    ],
    howToUse: "Carry over shoulder or by hand.",
    keyIngredients: ["Organic Cotton Canvas", "Artisan Weave", "Vegan Leather Accents"],
    skinType: ["Accessories"],
    inStock: true,
    stockCount: 12,
  },
  {
    slug: "noir-quilted-flap",
    name: "Noir Quilted Flap Handbag",
    brand: "koreanskincare.bd Luxe",
    category: "bags",
    price: 4890,
    was: 5900,
    img: prBag2,
    tag: "Limited",
    rating: 4.95,
    reviewCount: 78,
    volume: "Medium",
    variants: ["Noir Black"],
    description:
      "Classic quilted geometric design with luxury polished chain strap and timeless gold turn-lock closure.",
    benefits: [
      "Timeless chevron quilt",
      "Convertible double-chain strap",
      "Lined in luxury velvet",
    ],
    howToUse: "Adjust chain for short shoulder or long crossbody length.",
    keyIngredients: ["Diamond Quilted Vegan Leather", "Brass Hardware"],
    skinType: ["Accessories"],
    inStock: true,
    stockCount: 8,
  },
  {
    slug: "gold-pave-stack",
    name: "Gold Pavé Ring Stack (Set of 3)",
    brand: "koreanskincare.bd Jewelry",
    category: "rings",
    price: 1890,
    was: 2400,
    img: prRing1,
    tag: "Bestseller",
    rating: 4.88,
    reviewCount: 142,
    volume: "Ring Set",
    variants: ["Size 6", "Size 7", "Size 8"],
    description:
      "18k gold-plated hypoallergenic triple ring stack embedded with micro-cubic zirconia crystals.",
    benefits: [
      "Anti-tarnish coating",
      "Nickel-free & lead-free",
      "Wear together or across multiple fingers",
    ],
    howToUse: "Stack rings together or wear individually for a minimalist accent.",
    keyIngredients: ["18k Gold Plated Brass", "AAA Cubic Zirconia"],
    skinType: ["Jewelry"],
    inStock: true,
    stockCount: 22,
  },
  {
    slug: "rose-pearl-hoops",
    name: "Rosé Freshwater Pearl Hoops",
    brand: "koreanskincare.bd Jewelry",
    category: "earrings",
    price: 1490,
    was: 1890,
    img: prEar1,
    tag: "New",
    rating: 4.82,
    reviewCount: 64,
    volume: "Pair",
    variants: ["Rose Gold", "Yellow Gold", "Silver"],
    description:
      "Delicate huggie hoops featuring genuine baroque freshwater pearls that catch light beautifully.",
    benefits: [
      "Genuine baroque freshwater pearls",
      "Featherlight all-day comfort",
      "Hypoallergenic clasp",
    ],
    howToUse: "Click huggie clasp firmly into place.",
    keyIngredients: ["Freshwater Baroque Pearls", "Rose Gold Vermeil"],
    skinType: ["Jewelry"],
    inStock: true,
    stockCount: 15,
  },
  {
    slug: "ivory-classic-watch",
    name: "Ivory Classic Minimalist Watch",
    brand: "koreanskincare.bd Timepieces",
    category: "watches",
    price: 4990,
    was: 5900,
    img: catWatches,
    tag: "Bestseller",
    rating: 4.92,
    reviewCount: 88,
    volume: "34mm Dial",
    variants: ["Ivory / Gold", "Rose Gold Mesh"],
    description:
      "Japanese quartz movement with scratch-resistant sapphire crystal glass and genuine Italian leather strap.",
    benefits: [
      "Japanese Quartz Movement",
      "3ATM Water Resistant",
      "Italian Full-Grain Leather Strap",
    ],
    howToUse: "Adjust buckle to desired wrist fit.",
    keyIngredients: ["Stainless Steel 316L", "Sapphire Glass", "Italian Leather"],
    skinType: ["Timepieces"],
    inStock: true,
    stockCount: 10,
  },
];

export const HOMEPAGE_FEATURES: HomepageFeature[] = [
  { icon: "shield", title: "100% Authentic Import", summary: "Direct Seoul batch verified" },
  { icon: "truck", title: "24h Dhaka Express", summary: "Nationwide COD in 48-72h" },
  { icon: "refresh", title: "7-Day Easy Return", summary: "Hassle-free exchange policy" },
  { icon: "sparkles", title: "Dermatologist Tested", summary: "Gentle on sensitive skin" },
];

export const HOMEPAGE_TESTIMONIALS: HomepageTestimonial[] = [
  {
    name: "Dr. Sadia Rahman",
    city: "Dhaka",
    quote:
      "The COSRX Snail Mucin Essence transformed my skin barrier within 2 weeks. 100% authentic batch code, delivered in under 24 hours.",
  },
  {
    name: "Nusrat Khanom",
    city: "Chattogram",
    quote:
      "Beauty of Joseon Rice Sunscreen has zero white cast on Bangladeshi skin. KoreanSkincare.bd is now my holy-grail store for K-Beauty.",
  },
  {
    name: "Tasnia Chowdhury",
    city: "Sylhet",
    quote:
      "Super fast Cash on Delivery and genuine products directly imported from Korea. Best prices in Bangladesh with responsive customer support.",
  },
];

export const AUTH_PROVIDERS: AuthProvider[] = [
  {
    name: "Email & Password",
    status: "ready",
    description: "Primary authentication flow with secure session handling.",
  },
  {
    name: "Google Login",
    status: "ready",
    description: "Social sign-in for shoppers and staff accounts.",
  },
  {
    name: "Facebook Login",
    status: "planned",
    description: "Integration-ready provider slot for future rollout.",
  },
  {
    name: "OTP Login",
    status: "planned",
    description: "Phone and email OTP architecture reserved for expansion.",
  },
];

export const PAYMENT_GATEWAYS: PaymentGateway[] = [
  { name: "SSLCommerz", enabled: true },
  { name: "bKash", enabled: true },
  { name: "Nagad", enabled: true },
  { name: "Rocket", enabled: false },
  { name: "ShurjoPay", enabled: false },
  { name: "aamarPay", enabled: false },
  { name: "Cash on Delivery", enabled: true },
];

export const COURIER_PARTNERS: CourierPartner[] = [
  { name: "SteadFast", tracking: "Ready" },
  { name: "Pathao Courier", tracking: "Ready" },
  { name: "RedX", tracking: "Ready" },
  { name: "Sundarban", tracking: "Ready" },
  { name: "Paperfly", tracking: "Ready" },
];

export const CUSTOMER_MODULES: CustomerModule[] = [
  {
    title: "Dashboard Overview",
    description: "Orders, wallet, reward points, and recent activity at a glance.",
  },
  {
    title: "My Orders",
    description: "Track purchase status, delivery progress, and invoice downloads.",
  },
  {
    title: "Wishlist",
    description: "Save favorites across devices and move items to cart instantly.",
  },
  {
    title: "Addresses & Security",
    description: "Manage saved addresses, passwords, and account preferences.",
  },
];

export const ADMIN_MODULES: AdminModule[] = [
  { title: "Sales Analytics", description: "Revenue, conversion, AOV, and cohort views." },
  {
    title: "Products & Inventory",
    description: "Catalog, variants, stock, bulk edits, and media library.",
  },
  {
    title: "Homepage Builder",
    description: "Sections, banners, featured products, and publish controls.",
  },
  {
    title: "Operations",
    description: "Orders, payments, shipping, coupons, reviews, and audit logs.",
  },
];

export const HOMEPAGE_SETTINGS = {
  hero: {
    badge: "100% Authentic Korean Formulations",
    title: ["Radiant Glass Skin,", "Direct from Seoul."],
    description:
      "Clinically-proven Korean skincare essentials — snail mucin essences, soothing toners, lightweight SPF 50+ sunscreens, and ceramide barrier creams delivered anywhere in Bangladesh with Cash on Delivery.",
    primaryAction: "Shop K-Beauty Collection",
    secondaryAction: "Explore Categories",
    featuredLabel: "Seoul Bestseller Edit",
    featuredTitle: "COSRX Snail Mucin Essence",
  },
  categories: {
    eyebrow: "Shop by Step & Routine",
    title: "Essential K-Beauty Formulations",
  },
  bestsellers: {
    eyebrow: "Cult Favorites",
    title: "Most Loved by Bangladeshi Shoppers",
  },
  promise: {
    eyebrow: "The KoreanSkincare.bd Guarantee",
    title: ["100% Genuine Import,", "Clinically Proven Formulations."],
    description:
      "Every bottle is directly sourced from authorized Seoul laboratories and distributors. Batch-code verified, sealed packaging, and zero counterfeit compromise.",
    cta: "Discover Our Story",
  },
  freshDrops: {
    eyebrow: "New Arrivals",
    title: "Trending in Seoul This Season",
  },
  testimonials: {
    eyebrow: "Verified Buyer Stories",
    title: "Loved by 15,000+ Glowing Customers",
  },
  newsletter: {
    eyebrow: "Join the K-Beauty Club",
    title: "Exclusive Drops & Skincare Routine Guides",
    description:
      "Subscribe for early access to limited Seoul shipments and authentic skincare tips.",
  },
} as const;

export const NAV_LINKS = [
  { to: "/", label: "Home" },
  { to: "/shop", label: "Shop" },
  { to: "/shop", label: "Toners & Essences", params: { category: "toners" } },
  { to: "/shop", label: "Serums & Ampoules", params: { category: "serums" } },
  { to: "/about", label: "About" },
  { to: "/contact", label: "Contact" },
] as const;
